project:
  type: website

website:
  title: "Madelin Jauregui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: research.qmd
        text: Research
      - href: code.qmd
        text: Code
      - href: teaching.qmd
        text: Teaching
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/YOURUSERNAME
        aria-label: GitHub
      - icon: envelope
        href: mailto:YOUR_EMAIL@ucmerced.edu
        aria-label: Email
      - icon: journal
        href: https://surf-bar-eca.notion.site/PSY-010-Fall-26-2ef904f915f5805681a7ca1836149150
        aria-label: Teaching materials on Notion

format:
  html:
    theme:
      - cosmo
      - brand
    css:
      - styles.css
      - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css
    toc: true

execute:
  freeze: auto

editor: visual



